Controllers/ApoinmentController.cs
using HsptMS.Abstraction;
using HsptMS.Data.Models;
using HsptMS.Servises;
using Microsoft.AspNetCore.Mvc;

namespace HsptMS.Controllers
{
    public class ApoinmentController:Controller
    {
		private readonly IAppoinmentServises _appoinmentServises;
        private readonly HmsContext _hmscontext;
        public ApoinmentController(IAppoinmentServises appoinmentServises, HmsContext hmscontext)
        {
            _appoinmentServises = appoinmentServises;
            _hmscontext = hmscontext;
        }

        public ActionResult Index()
        {
            var appoinments= _appoinmentServises.Appointments();
            return View(appoinments);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Appointment appointment) 
        {
            _appoinmentServises.AddAppoinment(appointment);
            
            return RedirectToAction("Index");
        }


        public ActionResult Delete(Guid Id) 
        {
            var appoinment=_appoinmentServises.GetAppoinmentById(Id);
            return View(appoinment);
        }
        [HttpPost]
        public ActionResult DeleteConfirmed(Guid Id)
        {
            _appoinmentServises.RemoveAppoinment(Id);    
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid Id) 
        {
            var appointment = _appoinmentServises.GetAppoinmentById(Id);
            return View(appointment);
        }
        [HttpPost]
        public ActionResult Edit(Appointment appointment) 
        {
          _appoinmentServises.Update(appointment);
            return RedirectToAction("Index");
        }

        public ActionResult Details(Guid id) 
        {
            var appointment = _appoinmentServises.GetAppoinmentById(id);
            return View(appointment);
        }


    }
}

Controllers/BillingController.cs
using Microsoft.AspNetCore.Mvc;
using HsptMS.Data.Models;
using HsptMS.Services;
using System;
using HMS.Data.Extensions;

namespace HsptMS.Controllers
{
    public class BillingController : Controller
    {
        private readonly IBillingService _billingService;
        private readonly HmsContext _hmscontext;
        public BillingController(IBillingService billingService, HmsContext hmscontext) 
        {
            _billingService = billingService;
            _hmscontext = hmscontext;
        }
        public ActionResult Index() 
        {
            var displaay= _billingService.GetBillingList();
            return View(displaay); 
        }

        public ActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Billing billing)
        {
            billing.Id=GuidExtension.GetGuid();
             _billingService.AddBilling(billing);
            return RedirectToAction("Index");
        }


        public ActionResult Details(Guid id)
        {
            var billing = _billingService.GetBillingById(id);
            return View(billing);   
        }

        public ActionResult Edit(Guid id) 
        {
            var billing=_billingService.GetBillingById(id);
            return View(billing);
        }
        [HttpPost]
        public ActionResult Edit(Billing billing)
        {
            var billings=_billingService.GetBillingById(billing.Id);
            _billingService.RemoveBillingById(billings.Id);
            _billingService.AddBilling(billing);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            var billing=_billingService.GetBillingById(id);
            return View(billing);
        }
        [HttpPost]
        public ActionResult Delete(Billing billing)
        {
            var billings = _billingService.GetBillingById(billing.Id);
            _billingService.RemoveBillingById(billing.Id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/DoctorController.cs
using HsptMS.Abstraction;
using HsptMS.Data.Models;
using HsptMS.Servise;
using HsptMS.Servises;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics.Contracts;

namespace HsptMS.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorServise _doctorServise;
        private readonly HmsContext _hmscontext;
    
        public DoctorController(
            IDoctorServise doctorServise,
            HmsContext hmsContext
            )
        {
            _doctorServise = doctorServise;
            _hmscontext = hmsContext;
            
        }


        public ActionResult Index()
        {
            var doctors = _doctorServise.GetAllDoctorss();
            return View(doctors);
        }
         
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Doctor doctor)
        {
            //doctor.Id = GuidExtension.GetGuid();
            //doctor.DepartmentId = GuidExtension.GetGuid();
            var doctorList= _hmscontext.Doctors.ToList();
            ViewBag.DoctorId = new SelectList(doctorList, "Id", "Name");
            _doctorServise.AddDoctor(doctor);
            return RedirectToAction("Index");
        }

        public ActionResult Details(Guid id)
        {
            var doctor =_doctorServise.GetDoctorById(id);
            return View(doctor);
        }
        
        public ActionResult Edit(Guid id)
        {
            var doctor = _doctorServise.GetDoctorById(id);
            return View(doctor);
        }
        [HttpPost]
        public ActionResult Edit(Doctor doctor)
        {
            _doctorServise.UpdateDoctor(doctor);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            var doctor = _doctorServise.GetDoctorById(id);
            return View(doctor);
        }

        [HttpPost]
        
        public ActionResult DeleteConfirmed(Guid id)
        {
            _doctorServise.DeleteDoctor(id);
            return RedirectToAction("Index");
        }


    }

}

Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using HsptMS.Data.Models;
using FluentValidation.Results;

using HsptMS.Abstraction;
using HsptMS.Servises;
using FluentValidation;
using System.ComponentModel.DataAnnotations;
using FluentValidation.AspNetCore;
using System.Diagnostics.Metrics;
using ValidationResult = System.ComponentModel.DataAnnotations.ValidationResult;

namespace HsptMS.Controllers
{
    public class PatientController : Controller
    {
        public readonly HmsContext _hmsContext;
        private readonly IPatientService _patientService;
        private readonly IMasterService _masterService;
        private IValidator<Patient> _validator;

        public PatientController(
                 IPatientService patientService,
                 HmsContext hmsContext,
                 IMasterService masterService,
                 IValidator<Patient> validator
            )
        {
            _patientService = patientService;
            _hmsContext = hmsContext;
            _masterService = masterService;
            _validator = validator;

        }

        public async Task<IActionResult> Search(string searchString)
        {
            var patients = await _patientService.Search(searchString);


            return View("Index", patients);
        }
        public ActionResult Index()
        {
            var patients = _patientService.GetAllPatients();


            return View(patients);
        }

        public ActionResult Details(Guid id)
        {
            var patient = _patientService.GetPatientById(id);
            return View(patient);
        }

        public ActionResult Create()
        {
            ViewBag.GetDoctors = _masterService.GetDoctors();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Patient patient)
        {
            if (!ModelState.IsValid)
            {
                return View(patient);
            }
            _patientService.AddPatient(patient);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            ViewBag.GetDoctors = _masterService.GetDoctors();
            var patient = _patientService.GetPatientById(id);
            return View(patient);
        }

        [HttpPost]
        public ActionResult Edit(Patient patient)
        {
            _patientService.UpdatePatient(patient);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            var patient = _patientService.GetPatientById(id);
            return View(patient);
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(Guid id)
        {
            _patientService.DeletePatient(id);
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
@using HsptMS.Abstraction
@inject IContextService context;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HsptMS.styles.css" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css">
    <link rel="icon" type="image/x-icon" href="~/images/fav.ico" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css" />
    <!doctype html>
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <html lang="en" data-bs-theme="dark">
   
<link rel="icon" type="image/png" href="../images/Hspt.jpeg" />
</head>
<body>
   
   
<header>

       
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
                <img src="~/images/Hspt.jpeg"class="Logo-Image" style="border-radius:50px" alt="Alternate Text" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <nav  class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                   
                    <ul class="navbar-nav flex-grow-1">
                       
                         
                            <li class="nav-item">

                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                            </li>

                            <button id="themeSwitcher" class="btn btn-outline-secondary btn-sm">
                                <i id="themeIcon" class="bi bi-moon-fill"></i>
                            </button>
                    </ul>
                       
                    
                <ul class="navbar-nav flex-grow-1">  
                         @if (context.IsUserLoggedIn() == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patient</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctor</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Apoinment" asp-action="Index">Apoinment</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Billing" asp-action="Index">Billing</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>

                         }
                         else
                        {
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Signup">Register </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
                            </li>
                         } 
              </nav>
                        
        </div>

               
                        
    </nav>
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted" style="margin-top:20px;">
        <div class="container">
            &copy; 2024 - HsptMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> <a asp-area="" asp-controller="Home" asp-action="AboutMe">About Me</a>
        </div>
    </footer>*@
    
</body>
</html>



<script>
    document.addEventListener('DOMContentLoaded', function () {
        const themeSwitcher = document.getElementById('themeSwitcher');
        const themeIcon = document.getElementById('themeIcon');
        const navbar = document.querySelector('.navbar');
        const footer = document.querySelector('.footer');
        const currentTheme = localStorage.getItem('theme') || 'light';

        if (currentTheme === 'dark') {
            document.body.classList.add('bg-dark', 'text-light');
            navbar.classList.add('navbar-dark', 'bg-dark');
            footer.classList.add('bg-dark', 'text-light');
            themeIcon.classList.replace('bi-moon-fill', 'bi-sun-fill');
        }

        themeSwitcher.addEventListener('click', function () {
            document.body.classList.toggle('bg-dark');
            document.body.classList.toggle('text-light');
            navbar.classList.toggle('navbar-dark');
            navbar.classList.toggle('bg-dark');
            footer.classList.toggle('bg-dark');
            footer.classList.toggle('text-light');

            if (document.body.classList.contains('bg-dark')) {
                themeIcon.classList.replace('bi-moon-fill', 'bi-sun-fill');
                localStorage.setItem('theme', 'dark');
            } else {
                themeIcon.classList.replace('bi-sun-fill', 'bi-moon-fill');
                localStorage.setItem('theme', 'light');
            }
        });
    });
</script>